
services:

  # -----------------------------
  # Zookeeper (Kafka d√©pendance)
  # -----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -----------------------------
  # Kafka Broker
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # -----------------------------
  # Config Server
  # -----------------------------
  config-service:
    build:
      context: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service

  # -----------------------------
  # Discovery Service (Eureka)
  # -----------------------------
  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"

  # -----------------------------
  # Gateway Service
  # -----------------------------
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - config-service

  # -----------------------------
  # order Service
  # -----------------------------
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - kafka
      - config-service


  # -----------------------------
  # INVENTORY Service
  # -----------------------------
  inventory-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - kafka
      - config-service



  # -----------------------------
  # Data Analytics Service
  # -----------------------------
  data-analytics-service:
    build:
      context: ./data-analytics-service
    container_name: data-analytics-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - discovery-service
      - config-service

  # -----------------------------
  # Front Web App
  # -----------------------------
  frontweb-app:
    build:
      context: ./frontweb-app
    container_name: frontweb-app
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service
